project_id = "afnfyivevmqihuqijusi"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327
file_size_limit = "50MiB"
image_transformation = true

[auth]
enabled = true
port = 54328
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://afnfyivevmqihuqijusi.supabase.co/**"]
jwt_expiry = 3600
enable_signup = false

[edge_runtime]
enabled = true
port = 54329

[functions.ai-actions]
verify_jwt = false

[functions.audio-tts]
verify_jwt = false

[functions.offline-tts]
verify_jwt = false

[functions.python-tts]
verify_jwt = false

[functions.ai-document-analysis]
verify_jwt = false

[functions.document-qa]
verify_jwt = false