// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://afnfyivevmqihuqijusi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFmbmZ5aXZldm1xaWh1cWlqdXNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNzQ4MzAsImV4cCI6MjA3MDc1MDgzMH0.iZNTzN55MZK8p0hrZzsaAxbSALp5tVrloUQUiosmbRU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});